/*
 * @Author: zhangyanlong
 * @Date: 2021-03-19 01:37:07
 * @LastEditTime: 2021-03-19 01:38:16
 * @LastEditors: zhangyanlong
 * @Description:
 */
export const SET_COLLAPSE = 'SET_COLLAPSE';

export const GET_LIST_ENGINEER = 'GET_DATA_ENGINEER';
export const SET_LOADING_ENGINEER = 'SET_LOADING_ENGINEER';
export const SET_SEARCH_PARAMS_ENGINEER = 'SET_SEARCH_PARAMS_ENGINEER';
export const GET_CONFIG_ENGINEER = 'GET_CONFIG_ENGINEER';
export const SET_FORM_VISIABLE_ENGINEER = 'SET_FORM_VISIABLE_ENGINEER';
export const ADD_USER_ENGINEER = 'ADD_USER_ENGINEER';
export const SET_FORM_TYPE_ENGINEER = 'SET_FORM_TYPE_ENGINEER';
export const GET_DETAIL_ENGINEER = 'GET_DETAIL_ENGINEER';

export const GET_DATA_MAINBATCH = 'GET_DATA_MAINBATCH';
export const SET_LOADING_MAINBATCH = 'SET_LOADING_MAINBATCH';
export const SET_SEARCH_PARAMS_MAINBATCH = 'SET_SEARCH_PARAMS_MAINBATCH';
export const GET_CONFIG_MAINBATCH = 'GET_CONFIG_MAINBATCH';
export const SET_POSITIONS_MAINBATCH = 'SET_POSITIONS_MAINBATCH';
export const SET_MAXNUMBERS_MAINBATCH = 'SET_MAXNUMBERS_MAINBATCH';
export const SET_FORM_ADD_VISIABLE_MAINBATCH = 'SET_FORM_ADD_VISIABLE_MAINBATCH';
export const SET_DETAIL_MAINBATCH = 'SET_DETAIL_MAINBATCH';
export const SET_FORM_DETAIL_VISIABLE_MAINBATCH = 'SET_FORM_DETAIL_VISIABLE_MAINBATCH';
export const SET_FORM_EDIT_VISIABLE_MAINBATCH = 'SET_FORM_EDIT_VISIABLE_MAINBATCH';
export const SET_EDIT_DETAIL_MAINBATCH = 'SET_EDIT_DETAIL_MAINBATCH';

export const GET_DATA_SUBBATCH = 'GET_DATA_SUBBATCH';
export const SET_LOADING_SUBBATCH = 'SET_LOADING_SUBBATCH';
export const SET_SEARCH_PARAMS_SUBBATCH = 'SET_SEARCH_PARAMS_SUBBATCH';

export const GET_DATA_TEMPLATE = 'GET_DATA_TEMPLATE';
export const SET_LOADING_TEMPLATE = 'SET_LOADING_TEMPLATE';
export const SET_SEARCH_PARAMS_TEMPLATE = 'SET_SEARCH_PARAMS_TEMPLATE';
export const SET_CONFIG_TEMPLATE = 'SET_CONFIG_TEMPLATE';
export const SET_FORM_VISIABLE_TEMPLATE = 'SET_FORM_VISIABLE_TEMPLATE';
export const SET_FORM_TYPE_TEMPLATE = 'SET_FORM_TYPE_TEMPLATE';
export const SET_DETAIL_TEMPLATE = 'SET_DETAIL_TEMPLATE';
