/*
 * @Author: zhangyanlong
 * @Date: 2021-03-19 01:37:07
 * @LastEditTime: 2021-03-19 01:38:16
 * @LastEditors: zhangyanlong
 * @Description:
 */
export const SET_COLLAPSE = 'SET_COLLAPSE';

export const GET_LIST_ENGINEER = 'GET_DATA_ENGINEER';
export const SET_LOADING_ENGINEER = 'SET_LOADING_ENGINEER';
export const SET_SEARCH_PARAMS_ENGINEER = 'SET_SEARCH_PARAMS_ENGINEER';
export const GET_CONFIG_ENGINEER = 'GET_CONFIG_ENGINEER';
export const SET_FORM_VISIABLE_ENGINEER = 'SET_FORM_VISIABLE_ENGINEER';
export const ADD_USER_ENGINEER = 'ADD_USER_ENGINEER';
export const SET_FORM_TYPE_ENGINEER = 'SET_FORM_TYPE_ENGINEER';
export const GET_DETAIL_ENGINEER = 'GET_DETAIL_ENGINEER';

export const GET_DATA_SUBPATCH = 'GET_DATA_SUBPATCH';
export const SET_LOADING_SUBPATCH = 'SET_LOADING_SUBPATCH';
export const SET_SEARCH_PARAMS_SUBPATCH = 'SET_SEARCH_PARAMS_SUBPATCH';
